version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-network

  bank-app:
    build: .
    container_name: bank-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bank_cards
      - SPRING_DATASOURCE_USERNAME=bank_user
      - SPRING_DATASOURCE_PASSWORD=bank_password
    depends_on:
      - postgres
    networks:
      - bank-network

volumes:
  postgres_data:

networks:
  bank-network:
    driver: bridge