server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

logging:
  level:
    com.gshelgaas.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG